services:
  api-auto-up-release:
    image: registry.ft-soft.ru/devops/api-auto-up-release:latest
    ports:
      - "3001:3001"
    environment:
      AGENTS_JSON_PATH: ${AGENTS_JSON_PATH}
    volumes:
      - /opt/vneocheredi_auto_release_up/deploy_auto_up_release:/opt/vneocheredi_auto_release_up/deploy_auto_up_release
    networks:
      - network-auto-up-release

  web-auto-up-release:
    image: registry.ft-soft.ru/devops/web-auto-up-release:latest
    ports:
      - "8085:80"
    depends_on:
      - api-auto-up-release
    networks:
      - network-auto-up-release

networks:
  network-auto-up-release:
    name: network-auto-up-release
    external: true
