services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    networks:
      - web_auto_release
    restart: unless-stopped
    volumes:
      - rabbit_data_auto_release:/var/lib/rabbitmq/mnesia/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17.0
    hostname: postgres
    networks:
      - web_auto_release
    restart: unless-stopped
    volumes:
      - postgres_data_auto_release:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']

  master-postgres:
    image: postgres:17.2
    hostname: master-postgres
    shm_size: '8gb'
    networks:
      - web_auto_release
    restart: unless-stopped
    volumes:
      - master_postgres_data_auto_release:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MASTER_POSTGRES_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']

  migrator:
    image: ${VNEOCHEREDI_REGISTRY}/migrator:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Backoffice=Host=master-postgres;Database=JeFileBackoffice;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true;Command Timeout=1200;
      - ConnectionStrings__LogJeFile=Host=master-postgres;Database=JeFileLogs;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true;Command Timeout=1200;
      - ConnectionStrings__JeFileServer=Host=master-postgres;Database=JeFile;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true;Command Timeout=1200;
    depends_on:
      master-postgres:
        condition: service_healthy

  bouncer:
    image: registry.ft-soft.ru/infrastructure/pgbouncer:v1.24.0-p1
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - AUTH_TYPE=plain
      - DATABASE_URLS=postgres://postgres:${MASTER_POSTGRES_PASSWORD}@master-postgres/JeFileBackoffice,postgres://postgres:${MASTER_POSTGRES_PASSWORD}@master-postgres/JeFileLogs,postgres://postgres:${MASTER_POSTGRES_PASSWORD}@master-postgres/JeFile
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=3000
      - DEFAULT_POOL_SIZE=300
      - RESERVE_POOL_SIZE=50
    depends_on:
      master-postgres:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost']

  filestorage:
    image: ${VNEOCHEREDI_REGISTRY}/filestorage:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionString=Host=postgres;Database=JeFileFileStorage;Username=postgres;Password=${POSTGRES_PASSWORD};Include Error Detail=true
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  speech:
    image: ${VNEOCHEREDI_REGISTRY}/speech:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Database=Host=postgres;Database=JeFileSpeech;Username=postgres;Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__RabbitMq=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  server:
    image: ${VNEOCHEREDI_REGISTRY}/server:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Backoffice=Host=bouncer;Database=JeFileBackoffice;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__LogJeFile=Host=bouncer;Database=JeFileLogs;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__JeFileServer=Host=bouncer;Database=JeFile;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__RabbitMq=rabbitmq
      - ConnectionStrings__FileStorage=http://admin:8080/fileStorage
      # Настройки SMTP для Support
      - MailSettings__Support__Smtp__From=${SMTP_FROM}
      - MailSettings__Support__Smtp__Host=${SMTP_HOST}
      - MailSettings__Support__Smtp__Port=${SMTP_PORT}
      - MailSettings__Support__Smtp__UserName=${SMTP_USERNAME}
      - MailSettings__Support__Smtp__Password=${SMTP_PASSWORD}
      - MailSettings__Support__Smtp__EnableSsl=${SMTP_ENABLESSL}
      # Настройки SMTP для Rdv
      - MailSettings__Rdv__Smtp__From=${SMTP_FROM}
      - MailSettings__Rdv__Smtp__Host=${SMTP_HOST}
      - MailSettings__Rdv__Smtp__Port=${SMTP_PORT}
      - MailSettings__Rdv__Smtp__UserName=${SMTP_USERNAME}
      - MailSettings__Rdv__Smtp__Password=${SMTP_PASSWORD}
      - MailSettings__Rdv__Smtp__EnableSsl=${SMTP_ENABLESSL}
      # Настройки SMTP для Notification
      - MailSettings__Notification__Smtp__From=${SMTP_FROM}
      - MailSettings__Notification__Smtp__Host=${SMTP_HOST}
      - MailSettings__Notification__Smtp__Port=${SMTP_PORT}
      - MailSettings__Notification__Smtp__UserName=${SMTP_USERNAME}
      - MailSettings__Notification__Smtp__Password=${SMTP_PASSWORD}
      - MailSettings__Notification__Smtp__EnableSsl=${SMTP_ENABLESSL}
      # Различные переменные которые требуют универсальной внешей настройки через .env
      - AppSettings__RdvSite=${DNS_NAME_RDV}
    depends_on:
      bouncer:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  admin:
    image: ${VNEOCHEREDI_REGISTRY}/admin:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__Backoffice=Host=bouncer;Database=JeFileBackoffice;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__LogJeFile=Host=bouncer;Database=JeFileLogs;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__JeFileServer=Host=bouncer;Database=JeFile;Username=postgres;Password=${MASTER_POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__RabbitMq=rabbitmq
      - MailSettings__Support__Smtp__From=${SMTP_FROM}
      - MailSettings__Support__Smtp__Host=${SMTP_HOST}
      - MailSettings__Support__Smtp__Port=${SMTP_PORT}
      - MailSettings__Support__Smtp__UserName=${SMTP_USERNAME}
      - MailSettings__Support__Smtp__Password=${SMTP_PASSWORD}
      - MailSettings__Support__Smtp__EnableSsl=${SMTP_ENABLESSL}
      # Различные переменные которые требуют универсальной внешей настройки через .env
      - Terminal__TvLink=${DNS_NAME_CALL}/frame.html#/?language={language}&terminalId={monitorId}
      - Terminal__TvPocketLink=${DNS_NAME_CALL}/frame.html#/watchLinesMobile?language={language}&terminalId={monitorId}
      - RdvUrlForLinesList=${DNS_NAME_RDV}/#/{embeddedStyle}lines/{monitorId}
      - WebViewLink=${DNS_NAME_CALL}/inline.html#/settings?shopId={shopId}&theme={theme}&socket=true
      - WebViewAgentRequestStatisticsLink="${DNS_NAME_CALL}/inline.html#/settings?shopId={shopId}&language={language}&lineName={lineName}&serviceOnly=true&updateMs=30000"
    depends_on:
      server:
        condition: service_healthy
      bouncer:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  call:
    image: ${VNEOCHEREDI_REGISTRY}/call:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__RabbitMq=rabbitmq
      # Различные переменные которые требуют универсальной внешей настройки через .env
      - ApplicationSettings__JefileRdvHost=${DNS_NAME_RDV}
    depends_on:
      server:
        condition: service_healthy
      admin:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  portal:
    image: ${VNEOCHEREDI_REGISTRY}/rdv:${VNEOCHEREDI_VERSION}
    networks:
      - web_auto_release
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      server:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  telemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    volumes:
      - /:/hostfs
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=${HOST_NAME},deployment.environment=${HOST_NAME}
      - POSTGRES_PASSWORD=${MASTER_POSTGRES_PASSWORD}
    networks:
      - web_auto_release
    restart: unless-stopped
    command: --config /etc/otelcol-contrib/config.yaml


volumes:
  postgres_data_auto_release:
    name: postgres_data_auto_release_${VNEOCHEREDI_VERSION}
    external: true
  master_postgres_data_auto_release:
    name: master_postgres_data_auto_release_${VNEOCHEREDI_VERSION}
    external: true
  rabbit_data_auto_release:
    name: rabbit_data_auto_release_${VNEOCHEREDI_VERSION}
    external: true

networks:
  web_auto_release:
    name: web_auto_release_${VNEOCHEREDI_VERSION}
    external: true
