services:
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT_1}:15672"
      - "${RABBITMQ_PORT_2}:5672"
  postgres:
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Postgres/Backups:/var/backups
  master-postgres:
    ports:
      - "${MASTER_POSTGRES_PORT}:5432"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Postgres/Backups:/var/backups
  filestorage:
    ports:
      - "${FILE_STORAGE_PORT}:8080"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/FileStorage/Data:/app/Data
      - ${CONTAINER_DATA_PATH}/ContainersData/FileStorage/Settings/appsettings.json:/app/appsettings.json
  speech:
    ports:
      - "${SPEECH_PORT}:8080"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Speech/Data:/app/Data
      - ${CONTAINER_DATA_PATH}/ContainersData/Speech/Settings/appsettings.json:/app/appsettings.json
  server:
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Server/Data:/app/Data
      - ${CONTAINER_DATA_PATH}/ContainersData/Server/Settings/appsettings.json:/app/appsettings.json

  admin:
    ports:
      - "${ADMIN_PORT}:8080"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Admin/Files:/app/Files
      - ${CONTAINER_DATA_PATH}/ContainersData/Admin/Data:/app/Data
      - ${CONTAINER_DATA_PATH}/ContainersData/Admin/Settings/appsettings.json:/app/appsettings.json

  call:
    ports:
      - "${CALL_PORT}:8080"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Call/Data:/app/Data
      - ${CONTAINER_DATA_PATH}/ContainersData/Call/Settings/appsettings.json:/app/appsettings.json

  portal:
    ports:
      - "${PORTAL_PORT}:8080"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Rdv/Data:/app/Data
      - ${CONTAINER_DATA_PATH}/ContainersData/Rdv/Settings/appsettings.json:/app/appsettings.json
  
  telemetry-collector:
    ports:
      - "${TELEMETRY_COLLECTOR_PORT_1}:4317"
      - "${TELEMETRY_COLLECTOR_PORT_2}:4318"
    volumes:
      - ${CONTAINER_DATA_PATH}/ContainersData/Telemetry/sidecar-otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
